name: GeoNetwork Metadata Signoff Checklist
description: MAPS GeoNetwork Metadata Signoff Checklist
title: "[Dataset]: "
labels: ["documentation"]
assignees:
  - dzvoti
body:
  - type: markdown
    attributes:
      value: |
        |Key| Description|
        |-|-|
        |***|Mandatory, do not publish/sign-off without it|
        |**|High, the resource can be published but seek further information from MAPS contact person after signoff and update the record|
        |*|Low, the resource can be published without this detail|
  - type: checkboxes
    id: reource_name
    attributes:
      label: Resource Name***
      description: "Check if the name corresponds with the resource"
      options:
        - label: Sufficient for publication
        - label: Not sufficient for publication
          required: true      
  - type: dropdown
    id: reource_name2
    attributes:
      label: Resource Name***
      description: Check if the name corresponds with the resource
      options:
        - Sufficient for publication
        - Not sufficient for publication
    validations:
      required: true
  - type: checkboxes
    id: permission_publish
    attributes:
      label: Publish/Do not publish
      description: Overally is this metadata record sufficient for publication?
      options:
        - label: Sufficient
        - label: Not sufficient
          required: true
